#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -IBreakout/Freeimage/include -IBreakout/OpenGL/include
CFLAGS = -std=c++0x -Wall
RESINC = 
LIBDIR = -LBreakout/Freeimage/lib -LBreakout/OpenGL/lib
LIB = -lglfw -lGL -lGLU -lpthread -lXxf86vm -lGLEW -lfreeimage
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -D_DEBUG
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/Breakout

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -D_RELEASE
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/Breakout

OBJ_DEBUG = $(OBJDIR_DEBUG)/Breakout/Resource.o $(OBJDIR_DEBUG)/Breakout/ProgramGLSL.o $(OBJDIR_DEBUG)/Breakout/Physics.o $(OBJDIR_DEBUG)/Breakout/Pad.o $(OBJDIR_DEBUG)/Breakout/Skybox.o $(OBJDIR_DEBUG)/Breakout/ObjectCore.o $(OBJDIR_DEBUG)/Breakout/Object3D.o $(OBJDIR_DEBUG)/Breakout/Object2D.o $(OBJDIR_DEBUG)/Breakout/Model.o $(OBJDIR_DEBUG)/Breakout/Timer.o $(OBJDIR_DEBUG)/Breakout/Windowhandler.o $(OBJDIR_DEBUG)/Breakout/Water.o $(OBJDIR_DEBUG)/Breakout/UIElement.o $(OBJDIR_DEBUG)/Breakout/Texture.o $(OBJDIR_DEBUG)/Breakout/Text.o $(OBJDIR_DEBUG)/Breakout/TechniqueHLSL.o $(OBJDIR_DEBUG)/Breakout/EventSystem.o $(OBJDIR_DEBUG)/Breakout/Global.o $(OBJDIR_DEBUG)/Breakout/Gameplay.o $(OBJDIR_DEBUG)/Breakout/GameLogic.o $(OBJDIR_DEBUG)/Breakout/Font.o $(OBJDIR_DEBUG)/Breakout/Effect.o $(OBJDIR_DEBUG)/Breakout/Camera.o $(OBJDIR_DEBUG)/Breakout/Brick.o $(OBJDIR_DEBUG)/Breakout/MenuElement.o $(OBJDIR_DEBUG)/Breakout/Menu.o $(OBJDIR_DEBUG)/Breakout/Map.o $(OBJDIR_DEBUG)/Breakout/Main.o $(OBJDIR_DEBUG)/Breakout/Loader.o $(OBJDIR_DEBUG)/Breakout/Ball.o $(OBJDIR_DEBUG)/Breakout/LoadHandler.o $(OBJDIR_DEBUG)/Breakout/Inputhandler.o $(OBJDIR_DEBUG)/Breakout/GraphicsOGL4.o $(OBJDIR_DEBUG)/Breakout/GraphicsDX11.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/Breakout/Resource.o $(OBJDIR_RELEASE)/Breakout/ProgramGLSL.o $(OBJDIR_RELEASE)/Breakout/Physics.o $(OBJDIR_RELEASE)/Breakout/Pad.o $(OBJDIR_RELEASE)/Breakout/Skybox.o $(OBJDIR_RELEASE)/Breakout/ObjectCore.o $(OBJDIR_RELEASE)/Breakout/Object3D.o $(OBJDIR_RELEASE)/Breakout/Object2D.o $(OBJDIR_RELEASE)/Breakout/Model.o $(OBJDIR_RELEASE)/Breakout/Timer.o $(OBJDIR_RELEASE)/Breakout/Windowhandler.o $(OBJDIR_RELEASE)/Breakout/Water.o $(OBJDIR_RELEASE)/Breakout/UIElement.o $(OBJDIR_RELEASE)/Breakout/Texture.o $(OBJDIR_RELEASE)/Breakout/Text.o $(OBJDIR_RELEASE)/Breakout/TechniqueHLSL.o $(OBJDIR_RELEASE)/Breakout/EventSystem.o $(OBJDIR_RELEASE)/Breakout/Global.o $(OBJDIR_RELEASE)/Breakout/Gameplay.o $(OBJDIR_RELEASE)/Breakout/GameLogic.o $(OBJDIR_RELEASE)/Breakout/Font.o $(OBJDIR_RELEASE)/Breakout/Effect.o $(OBJDIR_RELEASE)/Breakout/Camera.o $(OBJDIR_RELEASE)/Breakout/Brick.o $(OBJDIR_RELEASE)/Breakout/MenuElement.o $(OBJDIR_RELEASE)/Breakout/Menu.o $(OBJDIR_RELEASE)/Breakout/Map.o $(OBJDIR_RELEASE)/Breakout/Main.o $(OBJDIR_RELEASE)/Breakout/Loader.o $(OBJDIR_RELEASE)/Breakout/Ball.o $(OBJDIR_RELEASE)/Breakout/LoadHandler.o $(OBJDIR_RELEASE)/Breakout/Inputhandler.o $(OBJDIR_RELEASE)/Breakout/GraphicsOGL4.o $(OBJDIR_RELEASE)/Breakout/GraphicsDX11.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/Breakout || mkdir -p $(OBJDIR_DEBUG)/Breakout

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/Breakout/Resource.o: Breakout/Resource.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Resource.cpp -o $(OBJDIR_DEBUG)/Breakout/Resource.o

$(OBJDIR_DEBUG)/Breakout/ProgramGLSL.o: Breakout/ProgramGLSL.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/ProgramGLSL.cpp -o $(OBJDIR_DEBUG)/Breakout/ProgramGLSL.o

$(OBJDIR_DEBUG)/Breakout/Physics.o: Breakout/Physics.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Physics.cpp -o $(OBJDIR_DEBUG)/Breakout/Physics.o

$(OBJDIR_DEBUG)/Breakout/Pad.o: Breakout/Pad.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Pad.cpp -o $(OBJDIR_DEBUG)/Breakout/Pad.o

$(OBJDIR_DEBUG)/Breakout/Skybox.o: Breakout/Skybox.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Skybox.cpp -o $(OBJDIR_DEBUG)/Breakout/Skybox.o

$(OBJDIR_DEBUG)/Breakout/ObjectCore.o: Breakout/ObjectCore.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/ObjectCore.cpp -o $(OBJDIR_DEBUG)/Breakout/ObjectCore.o

$(OBJDIR_DEBUG)/Breakout/Object3D.o: Breakout/Object3D.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Object3D.cpp -o $(OBJDIR_DEBUG)/Breakout/Object3D.o

$(OBJDIR_DEBUG)/Breakout/Object2D.o: Breakout/Object2D.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Object2D.cpp -o $(OBJDIR_DEBUG)/Breakout/Object2D.o

$(OBJDIR_DEBUG)/Breakout/Model.o: Breakout/Model.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Model.cpp -o $(OBJDIR_DEBUG)/Breakout/Model.o

$(OBJDIR_DEBUG)/Breakout/Timer.o: Breakout/Timer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Timer.cpp -o $(OBJDIR_DEBUG)/Breakout/Timer.o

$(OBJDIR_DEBUG)/Breakout/Windowhandler.o: Breakout/Windowhandler.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Windowhandler.cpp -o $(OBJDIR_DEBUG)/Breakout/Windowhandler.o

$(OBJDIR_DEBUG)/Breakout/Water.o: Breakout/Water.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Water.cpp -o $(OBJDIR_DEBUG)/Breakout/Water.o

$(OBJDIR_DEBUG)/Breakout/UIElement.o: Breakout/UIElement.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/UIElement.cpp -o $(OBJDIR_DEBUG)/Breakout/UIElement.o

$(OBJDIR_DEBUG)/Breakout/Texture.o: Breakout/Texture.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Texture.cpp -o $(OBJDIR_DEBUG)/Breakout/Texture.o

$(OBJDIR_DEBUG)/Breakout/Text.o: Breakout/Text.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Text.cpp -o $(OBJDIR_DEBUG)/Breakout/Text.o

$(OBJDIR_DEBUG)/Breakout/TechniqueHLSL.o: Breakout/TechniqueHLSL.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/TechniqueHLSL.cpp -o $(OBJDIR_DEBUG)/Breakout/TechniqueHLSL.o

$(OBJDIR_DEBUG)/Breakout/EventSystem.o: Breakout/EventSystem.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/EventSystem.cpp -o $(OBJDIR_DEBUG)/Breakout/EventSystem.o

$(OBJDIR_DEBUG)/Breakout/Global.o: Breakout/Global.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Global.cpp -o $(OBJDIR_DEBUG)/Breakout/Global.o

$(OBJDIR_DEBUG)/Breakout/Gameplay.o: Breakout/Gameplay.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Gameplay.cpp -o $(OBJDIR_DEBUG)/Breakout/Gameplay.o

$(OBJDIR_DEBUG)/Breakout/GameLogic.o: Breakout/GameLogic.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/GameLogic.cpp -o $(OBJDIR_DEBUG)/Breakout/GameLogic.o

$(OBJDIR_DEBUG)/Breakout/Font.o: Breakout/Font.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Font.cpp -o $(OBJDIR_DEBUG)/Breakout/Font.o

$(OBJDIR_DEBUG)/Breakout/Effect.o: Breakout/Effect.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Effect.cpp -o $(OBJDIR_DEBUG)/Breakout/Effect.o

$(OBJDIR_DEBUG)/Breakout/Camera.o: Breakout/Camera.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Camera.cpp -o $(OBJDIR_DEBUG)/Breakout/Camera.o

$(OBJDIR_DEBUG)/Breakout/Brick.o: Breakout/Brick.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Brick.cpp -o $(OBJDIR_DEBUG)/Breakout/Brick.o

$(OBJDIR_DEBUG)/Breakout/MenuElement.o: Breakout/MenuElement.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/MenuElement.cpp -o $(OBJDIR_DEBUG)/Breakout/MenuElement.o

$(OBJDIR_DEBUG)/Breakout/Menu.o: Breakout/Menu.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Menu.cpp -o $(OBJDIR_DEBUG)/Breakout/Menu.o

$(OBJDIR_DEBUG)/Breakout/Map.o: Breakout/Map.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Map.cpp -o $(OBJDIR_DEBUG)/Breakout/Map.o

$(OBJDIR_DEBUG)/Breakout/Main.o: Breakout/Main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Main.cpp -o $(OBJDIR_DEBUG)/Breakout/Main.o

$(OBJDIR_DEBUG)/Breakout/Loader.o: Breakout/Loader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Loader.cpp -o $(OBJDIR_DEBUG)/Breakout/Loader.o

$(OBJDIR_DEBUG)/Breakout/Ball.o: Breakout/Ball.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Ball.cpp -o $(OBJDIR_DEBUG)/Breakout/Ball.o

$(OBJDIR_DEBUG)/Breakout/LoadHandler.o: Breakout/LoadHandler.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/LoadHandler.cpp -o $(OBJDIR_DEBUG)/Breakout/LoadHandler.o

$(OBJDIR_DEBUG)/Breakout/Inputhandler.o: Breakout/Inputhandler.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/Inputhandler.cpp -o $(OBJDIR_DEBUG)/Breakout/Inputhandler.o

$(OBJDIR_DEBUG)/Breakout/GraphicsOGL4.o: Breakout/GraphicsOGL4.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/GraphicsOGL4.cpp -o $(OBJDIR_DEBUG)/Breakout/GraphicsOGL4.o

$(OBJDIR_DEBUG)/Breakout/GraphicsDX11.o: Breakout/GraphicsDX11.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Breakout/GraphicsDX11.cpp -o $(OBJDIR_DEBUG)/Breakout/GraphicsDX11.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/Breakout

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/Breakout || mkdir -p $(OBJDIR_RELEASE)/Breakout

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/Breakout/Resource.o: Breakout/Resource.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Resource.cpp -o $(OBJDIR_RELEASE)/Breakout/Resource.o

$(OBJDIR_RELEASE)/Breakout/ProgramGLSL.o: Breakout/ProgramGLSL.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/ProgramGLSL.cpp -o $(OBJDIR_RELEASE)/Breakout/ProgramGLSL.o

$(OBJDIR_RELEASE)/Breakout/Physics.o: Breakout/Physics.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Physics.cpp -o $(OBJDIR_RELEASE)/Breakout/Physics.o

$(OBJDIR_RELEASE)/Breakout/Pad.o: Breakout/Pad.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Pad.cpp -o $(OBJDIR_RELEASE)/Breakout/Pad.o

$(OBJDIR_RELEASE)/Breakout/Skybox.o: Breakout/Skybox.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Skybox.cpp -o $(OBJDIR_RELEASE)/Breakout/Skybox.o

$(OBJDIR_RELEASE)/Breakout/ObjectCore.o: Breakout/ObjectCore.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/ObjectCore.cpp -o $(OBJDIR_RELEASE)/Breakout/ObjectCore.o

$(OBJDIR_RELEASE)/Breakout/Object3D.o: Breakout/Object3D.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Object3D.cpp -o $(OBJDIR_RELEASE)/Breakout/Object3D.o

$(OBJDIR_RELEASE)/Breakout/Object2D.o: Breakout/Object2D.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Object2D.cpp -o $(OBJDIR_RELEASE)/Breakout/Object2D.o

$(OBJDIR_RELEASE)/Breakout/Model.o: Breakout/Model.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Model.cpp -o $(OBJDIR_RELEASE)/Breakout/Model.o

$(OBJDIR_RELEASE)/Breakout/Timer.o: Breakout/Timer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Timer.cpp -o $(OBJDIR_RELEASE)/Breakout/Timer.o

$(OBJDIR_RELEASE)/Breakout/Windowhandler.o: Breakout/Windowhandler.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Windowhandler.cpp -o $(OBJDIR_RELEASE)/Breakout/Windowhandler.o

$(OBJDIR_RELEASE)/Breakout/Water.o: Breakout/Water.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Water.cpp -o $(OBJDIR_RELEASE)/Breakout/Water.o

$(OBJDIR_RELEASE)/Breakout/UIElement.o: Breakout/UIElement.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/UIElement.cpp -o $(OBJDIR_RELEASE)/Breakout/UIElement.o

$(OBJDIR_RELEASE)/Breakout/Texture.o: Breakout/Texture.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Texture.cpp -o $(OBJDIR_RELEASE)/Breakout/Texture.o

$(OBJDIR_RELEASE)/Breakout/Text.o: Breakout/Text.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Text.cpp -o $(OBJDIR_RELEASE)/Breakout/Text.o

$(OBJDIR_RELEASE)/Breakout/TechniqueHLSL.o: Breakout/TechniqueHLSL.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/TechniqueHLSL.cpp -o $(OBJDIR_RELEASE)/Breakout/TechniqueHLSL.o

$(OBJDIR_RELEASE)/Breakout/EventSystem.o: Breakout/EventSystem.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/EventSystem.cpp -o $(OBJDIR_RELEASE)/Breakout/EventSystem.o

$(OBJDIR_RELEASE)/Breakout/Global.o: Breakout/Global.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Global.cpp -o $(OBJDIR_RELEASE)/Breakout/Global.o

$(OBJDIR_RELEASE)/Breakout/Gameplay.o: Breakout/Gameplay.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Gameplay.cpp -o $(OBJDIR_RELEASE)/Breakout/Gameplay.o

$(OBJDIR_RELEASE)/Breakout/GameLogic.o: Breakout/GameLogic.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/GameLogic.cpp -o $(OBJDIR_RELEASE)/Breakout/GameLogic.o

$(OBJDIR_RELEASE)/Breakout/Font.o: Breakout/Font.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Font.cpp -o $(OBJDIR_RELEASE)/Breakout/Font.o

$(OBJDIR_RELEASE)/Breakout/Effect.o: Breakout/Effect.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Effect.cpp -o $(OBJDIR_RELEASE)/Breakout/Effect.o

$(OBJDIR_RELEASE)/Breakout/Camera.o: Breakout/Camera.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Camera.cpp -o $(OBJDIR_RELEASE)/Breakout/Camera.o

$(OBJDIR_RELEASE)/Breakout/Brick.o: Breakout/Brick.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Brick.cpp -o $(OBJDIR_RELEASE)/Breakout/Brick.o

$(OBJDIR_RELEASE)/Breakout/MenuElement.o: Breakout/MenuElement.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/MenuElement.cpp -o $(OBJDIR_RELEASE)/Breakout/MenuElement.o

$(OBJDIR_RELEASE)/Breakout/Menu.o: Breakout/Menu.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Menu.cpp -o $(OBJDIR_RELEASE)/Breakout/Menu.o

$(OBJDIR_RELEASE)/Breakout/Map.o: Breakout/Map.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Map.cpp -o $(OBJDIR_RELEASE)/Breakout/Map.o

$(OBJDIR_RELEASE)/Breakout/Main.o: Breakout/Main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Main.cpp -o $(OBJDIR_RELEASE)/Breakout/Main.o

$(OBJDIR_RELEASE)/Breakout/Loader.o: Breakout/Loader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Loader.cpp -o $(OBJDIR_RELEASE)/Breakout/Loader.o

$(OBJDIR_RELEASE)/Breakout/Ball.o: Breakout/Ball.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Ball.cpp -o $(OBJDIR_RELEASE)/Breakout/Ball.o

$(OBJDIR_RELEASE)/Breakout/LoadHandler.o: Breakout/LoadHandler.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/LoadHandler.cpp -o $(OBJDIR_RELEASE)/Breakout/LoadHandler.o

$(OBJDIR_RELEASE)/Breakout/Inputhandler.o: Breakout/Inputhandler.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/Inputhandler.cpp -o $(OBJDIR_RELEASE)/Breakout/Inputhandler.o

$(OBJDIR_RELEASE)/Breakout/GraphicsOGL4.o: Breakout/GraphicsOGL4.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/GraphicsOGL4.cpp -o $(OBJDIR_RELEASE)/Breakout/GraphicsOGL4.o

$(OBJDIR_RELEASE)/Breakout/GraphicsDX11.o: Breakout/GraphicsDX11.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Breakout/GraphicsDX11.cpp -o $(OBJDIR_RELEASE)/Breakout/GraphicsDX11.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/Breakout

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

